name: Rules and/or Guidelines issue
description: Report a problem with the Rules and/or Guidelines
title: "[Rules and Guideline] <title>"
labels: ["Rules and Guideline"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the problem you're reporting.
    options:
    - label: I have searched for existing issues and did not find anything like it
      required: true

- type: textarea
  attributes:
    label: Which Rule and/or Guideline has a problem?
    description: |
      For which Rule and/or Guidelines you reporting?

      Tip: Quote the Rule and/or Guideline in this section.
  validations:
    required: true

- type: textarea
  attributes:
    label: What is wrong with the Rule and/or Guideline?
    description: |
      Please the problem with the Rule and/or Guideline.
  validations:
    required: true

- type: textarea
  attributes:
    label: How do you recommend we fix the problem?
    description: |
      Please suggest how we might fix the Rules and/or Guidelines.

      Tip: Suggest alternate language for the Rule and/or Guideline.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Do you have any additional context or information?

      Tip: you can attach files by clicking the text area to highlight it and then click the link that says paste, drop or click to add files.
  validations:
    required: false

